/* /etc/X11/xorg.conf.d/00-keyboard.conf */
Section "InputClass"
Identifier "system-keyboard"
MatchIsKeyboard "on"
Option "XkbLayout" "us"
EndSection

/* /etc/X11/xorg.conf.d/optimus.conf */
Section "Module"
    Load "modesetting"
EndSection

Section "Device"
    Identifier "nvidia"
    Driver "nvidia"
    BusID "PCI:1:0:0"
    Option "AllowEmptyInitialConfiguration"
EndSection

/* /etc/modprobe.d/nvidia.conf */
blacklist nouveau
blacklist nvidiafb
blacklist rivafb
options nvidia "NVreg_DynamicPowerManagement=0x02"

/* /etc/modprobe.d/nvidia-drm.conf */
options nvidia_drm modeset=1

/* /etc/modprobe.d/system76-driver_i2c-nvidia-gpu.conf */
blacklist i2c_nvidia_gpu

/* /etc/modprobe.d/system76-power.conf */
# Automatically generated by system76-power

/* /etc/modules-load.d/modules.conf */
# List of modules to load at boot

/* /etc/modules-load.d/system76-acpi.conf */
# Load the System76 ACPI module
system76-acpi

/* /etc/modules-load.d/system76.conf */
# Load the system76 driver module
system76

/* /etc/modules-load.d/system76-io.conf */
# Load the system76-io driver module
system76-io